### ISSUE TITLE
Rescan can fail when the year isn't ISO formatted

### ISSUE THREAD

**Issue by charvp** [accentor/api#157]
- [x] There are no similar issues reported yet

**Describe the bug**
```
invalid date
/api/app/models/rescan_runner.rb:179:in `initialize'
/api/app/models/rescan_runner.rb:179:in `new'
/api/app/models/rescan_runner.rb:179:in `convert_year'
/api/app/models/rescan_runner.rb:87:in `process_file'
```

**To Reproduce**
Create a file with the following date set "12-15-20" and scan it.

**Expected behavior**
Should at least scan. (I don't think we need to parse all dates, they can be ambiguous anyway.)

**Comment by robbevp** [comment]
Would you set the date to 0000-01-01 if we can’t parse it as ISO? Id3’s spec specifies an iso format for dates, so technically these tags are invalid.
We can make a few edge cases, but can’t account for all possible date formats (since we can’t know whether 02-01-20 is dd-mm-yy- or mm-dd-yy)

**Comment by charvp** [comment]
Yeah, parsing as 0000-01-01 is fine.
