### ISSUE TITLE
Add play count for tracks

### ISSUE THREAD

**Issue by robbevp** [accentor/api#16]

**Comment by charvp** [comment]
We probably want a database record per play. Would allow us to generate more interesting statistics afterwards.

**Comment by robbevp** [comment]
> We probably want a database record per play. Would allow us to generate more interesting statistics afterwards.

Is there something stopping us from adding this in 1.0?
If this is per play, this will always be a table with `user_id`, `datetime` and `track_id`, so the way this is implemented in the various apps shouldn't matter much.

**Comment by charvp** [comment]
The reason I'm hesitant with adding features to the API for 1.0 is that I want all clients to have at least basic support for all server features. So adding a feature to the API would create extra work for the android client and the (yet to be started) desktop client.

My idea was also to make 1.0 have a minimal feature set that has everything that is absolutely essential, but not much more than that.
