### ISSUE TITLE
Not all images have same cache headers

### ISSUE THREAD

**Issue by robbevp** [accentor/api#165]
**Describe the bug**
The cache headers vary for different images. I've not been able to determine a clear pattern yet.

**To Reproduce**

1. Go to web frontend and browse through some albums
2. Open network tab from devtools and inspect request for images
3. Some images have status code 304 and have the cache-control headers set to `no-cache`
4. Some images have status code 302 and have the cache-control headers set to `max-age=300, private`

**Expected behavior**
All images should be served with same cache headers

**Comment by charvp** [comment]
Can't reproduce. I have 302 and max-age=300 for all images.

**Comment by robbevp** [comment]
I'll investigate further. What browser did you use to try?On 25 Dec 2020 20:15, Charlotte Van Petegem <notifications@github.com> wrote:
Can't reproduce. I have 302 and max-age=300 for all images.

**Comment by charvp** [comment]
Firefox

**Comment by robbevp** [comment]
I've looked into this a bit more.

For each image displayed there are two requests happening:
1. A request to the `rails_representation_url` (`/rails/active_storage/representations/redirect/:key/:filename`). This has the correct headers and returns the location of the image itself (`/rails/active_storage/disk/:key/:filename`) with 302 as a status.
2. A request for the image itself, base on the redirect we got earlier. This usually has status 200, though chrome seems to report 304 if the redirect location was cached.

While the first request seems to allow caching: `cache-control: max-age=300, private`. The second request does not: `cache-control: max-age=0, private, must-revalidate`. (If Chrome reports 304, it has `no-cache`).

The result seems to be that images aren't cached. If I inspect the usage of the application in FF or chrome, the amount of data used seems to low or it to contain any images. An image can still be requested multiple times wihtin one session and seems to be rerequested for each new session.

**Comment by chvp** [comment]
I don't think there is a problem here? `max-age=0, private, must-revalidate` means that the browser must send a new request (with the `If-Modified-Since` header) if the resource is requested again. The 304 response means "Not modified" a.k.a. "You can use the cached resource".

**Comment by robbevp** [comment]
Yes, I think we can close this
