### ISSUE TITLE
Album release is not enforced through validation but is presumed to be present

### ISSUE THREAD

**Issue by robbevp** [accentor/api#323]
We're not very consistent in the presence of an album's release attribute:
In the API:
* We don't validate it's presence in the model validations
* Don't set a release date in the factory
* But do provide a default value `Date.new(0)` is the tag is missing in the rescan runner

In the API-client lib:
* We make the date as non-optional, both in the params as the returned type  
https://github.com/accentor/api-client-js/blob/main/src/types/album.ts#L6
https://github.com/accentor/api-client-js/blob/main/src/types/album.ts#L21

In the web interface:
* We assume the release date to be present and have uncatched errors if it is missing  
One example: 
https://github.com/accentor/web/blob/main/src/components/AlbumCard.vue#L31

##### Reproduction steps

  1. Create an album with factory (in your dev DB obv.)
  2. Go to web interface
  3. Notice errors in console, due to release being `null`

##### Expected behaviour
We should either:
* Treat the release date as optional, and update the api-client lib and web interface
* Enforce the presence in the model and update the factory

**Comment by chvp** [comment]
Enforcing presence in the model seems like the best option to me. I think I meant to do so when initially creating the model.

**Comment by robbevp** [comment]
> Enforcing presence in the model seems like the best option to me. I think I meant to do so when initially creating the model.

Would you just throw an error or jus set a default (which means that we could remove the default value from the RescanRunner model)
