### ISSUE TITLE
Add bit depth and sample rate to audio file

### ISSUE THREAD

**Issue by robbevp** [accentor/api#52]
Will be relevant for Accentor/web#33

**Comment by robbevp** [comment]
TagLib already supports [bitsPerSample](https://taglib.org/api/classTagLib_1_1FLAC_1_1Properties.html#a31aef71dcbb534b7dff4ca297aad20b8) and [sampleRate](https://taglib.org/api/classTagLib_1_1FLAC_1_1Properties.html#abca04dd6c93f1b76cf2163c90078d088) so this shouldn't be too difficult.
We will have to figure out how to update all of the existing audio_file obejcts

**Comment by charvp** [comment]
I really don't see how this would be useful for tagging/resolving conflicts, which is the reason for https://github.com/accentor/web/issues/33.

**Comment by robbevp** [comment]
It will help the user in determining which file(s) to keep. We can't expect/suppose that the filename will include this information
