### ISSUE TITLE
Experiment with wahwah for reading audio metadata

### ISSUE THREAD

**Issue by charvp** [accentor/api#66]
The current library, easytag, is unmaintained, so [wahwah](https://github.com/aidewoode/wahwah) might be a good alternative.

**Comment by robbevp** [comment]
We might also look into [taglib-ruby](https://github.com/robinst/taglib-ruby), one of the dependencies of easytag, which released 1.0 earlier this year.

**Comment by charvp** [comment]
The problem with taglib-ruby is that we would have to handle file types ourselves to get all the info we need.

**Comment by robbevp** [comment]
Yeah, I haven't looked into it in detail.
I just tried a first test with WahWah. Seems to pass all our current tests without problems
